FROM ubuntu:latest

USER root
ENV USER root

# Install package dependencies.
RUN apt-get update \
    && apt-get install -y \
    apt-utils \
    curl \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl https://sh.rustup.rs -sSf > /tmp/rustup-init.sh \
    && chmod +x /tmp/rustup-init.sh \
    && sh /tmp/rustup-init.sh -y \
    && rm -rf /tmp/rustup-init.sh
ENV PATH "$PATH:~/.cargo/bin"

# Update the local crate index
RUN ~/.cargo/bin/cargo search

# Install nightly rust.
RUN ~/.cargo/bin/rustup install nightly

RUN mkdir -p /blockchain_src

WORKDIR /blockchain_src

COPY ./src /blockchain_src/src
COPY ./.env-docker /blockchain_src/
COPY ./.env /blockchain_src/
COPY ./Cargo.toml ./Cargo.lock /blockchain_src/

RUN ~/.cargo/bin/cargo build

RUN ~/.cargo/bin/cargo run docker
