FROM rust:1.38.0 AS build

RUN rustup target add x86_64-unknown-linux-musl

RUN apt-get install -y musl-gcc

RUN mkdir -p /blockchain_src

WORKDIR /blockchain_src

COPY ./src /blockchain_src/src
COPY ./.env-docker /blockchain_src/
COPY ./.env /blockchain_src/
COPY ./Cargo.toml ./Cargo.lock /blockchain_src/

RUN cargo build --release

RUN cargo install --target x86_64-unknown-linux-musl --path .

FROM scratch

RUN apt-get install -y musl-gcc

COPY --from=build /usr/local/cargo/bin/blockchain-rust .

USER 1000

CMD ["./blockchain-rust docker"]
