FROM ubuntu:latest

USER root
ENV USER root

# Install package dependencies.
RUN apt-get update \
    && apt-get install -y \
    apt-utils \
    curl \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl https://sh.rustup.rs -sSf > /tmp/rustup-init.sh \
    && chmod +x /tmp/rustup-init.sh \
    && sh /tmp/rustup-init.sh -y \
    && rm -rf /tmp/rustup-init.sh

ENV PATH "$PATH:~/.cargo/bin"

# Update the local crate index
RUN ~/.cargo/bin/cargo search

# Install rust 1.38.0
RUN ~/.cargo/bin/rustup install 1.38.0

RUN mkdir -p /blockchain-rust

WORKDIR /blockchain-rust

COPY ./src /blockchain-rust/src
COPY ./.env-docker /blockchain-rust/
COPY ./.env /blockchain-rust/
COPY ./Cargo.toml ./Cargo.lock /blockchain-rust/

RUN ~/.cargo/bin/cargo build

#RUN ~/.cargo/bin/cargo run docker
