name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sergiomtzlosa/blockchain-satellite@master
      with:
        args: cargo build --verbose && cargo test --verbose
