name: Rust build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.31.0
    name: "compile"
    steps:
    - uses: sergiomtzlosa/blockchain-satellite@master
      with:
        args: cargo build --verbose && cargo test --verbose
