name: Rust build
on: [push]
jobs:
  build:
    name: Compilation Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Blockchain rust compilation
        run: |
          cargo build --verbose && cargo test --verbose
